<!--button-->
<div class="btn">
    <button id="open_modal">Open Modal</button>
    <button id="magento_login_modal" value="">Open Magento Login Modal</button>
</div>
<!--Form-->
<div id="form_login">
    <form class="my_form" method="get">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>
        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>
    </form>
</div>
